package com.runecalculator;

import lombok.Getter;

import net.runelite.api.gameval.SpriteID;

import java.util.EnumSet;

import static com.runecalculator.RuneTypes.*;

@Getter
public enum SpellData
{
    WIND_STRIKE("Wind Strike", SpriteID.Magicon.WIND_STRIKE, AIR, MIND),
    CONFUSE("Confuse", SpriteID.Magicon.CONFUSE, WATER, EARTH, BODY),
    ENCHANT_OPAL_BOLT("Enchant Opal Bolt", SpriteID.Magicon2.ENCHANT_CROSSBOW_BOLT, AIR, COSMIC),
    WATER_STRIKE("Water Strike", SpriteID.Magicon.WATER_STRIKE, AIR, WATER, MIND),
    ARCEUUS_LIBRARY_TELEPORT("Arceuus Library Teleport", SpriteID.MagicNecroOn.ARCEUUS_LIBRARY_TELEPORT, EARTH, LAW),
    ENCHANT_SAPPHIRE_BOLT("Enchant Sapphire Bolt", SpriteID.Magicon2.ENCHANT_CROSSBOW_BOLT, WATER, COSMIC, MIND),
    ENCHANT_SAPPHIRE_JEWELLERY("Enchant Sapphire Jewellery", SpriteID.Magicon.LVL_1_ENCHANT, WATER, COSMIC),
    EARTH_STRIKE("Earth Strike", SpriteID.Magicon.EARTH_STRIKE, AIR, EARTH, MIND),
    WEAKEN("Weaken", SpriteID.Magicon.WEAKEN, EARTH, WATER, BODY),
    FIRE_STRIKE("Fire Strike", SpriteID.Magicon.FIRE_STRIKE, AIR, FIRE, MIND),
    ENCHANT_JADE_BOLT("Enchant Jade Bolt", SpriteID.Magicon2.ENCHANT_CROSSBOW_BOLT, EARTH, COSMIC),
    BONES_TO_BANANAS("Bones To Bananas", SpriteID.Magicon.BONES_TO_BANANAS, EARTH, WATER, NATURE),
    BASIC_REANIMATION("Basic Reanimation", SpriteID.MagicNecroOn.BASIC_REANIMATION, BODY, NATURE),
    WIND_BOLT("Wind Bolt", SpriteID.Magicon.WIND_BOLT, AIR, CHAOS),
    DRAYNOR_MANOR_TELEPORT("Draynor Manor Teleport", SpriteID.MagicNecroOn.DRAYNOR_MANOR_TELEPORT, EARTH, WATER, LAW),
    CURSE("Curse", SpriteID.Magicon.CURSE, EARTH, WATER, BODY),
    BIND("Bind", SpriteID.Magicon2.BIND, EARTH, WATER, NATURE),
    LOW_LEVEL_ALCHEMY("Low Level Alchemy", SpriteID.Magicon.LOW_LEVEL_ALCHEMY, FIRE, NATURE),
    WATER_BOLT("Water Bolt", SpriteID.Magicon.WATER_BOLT, AIR, WATER, CHAOS),
    ENCHANT_PEARL_BOLT("Enchant Pearl Bolt", SpriteID.Magicon2.ENCHANT_CROSSBOW_BOLT, WATER, COSMIC),
    VARROCK_TELEPORT("Varrock Teleport", SpriteID.Magicon.VARROCK_TELEPORT, AIR, FIRE, LAW),
    ENCHANT_EMERALD_BOLT("Enchant Emerald Bolt", SpriteID.Magicon2.ENCHANT_CROSSBOW_BOLT, AIR, COSMIC, NATURE),
    ENCHANT_EMERALD_JEWELLERY("Enchant Emerald Jewellery", SpriteID.Magicon.LVL_2_ENCHANT, AIR, COSMIC),
    MIND_ALTAR_TELEPORT("Mind Altar Teleport", SpriteID.MagicNecroOn.MIND_ALTAR_TELEPORT, LAW, MIND),
    EARTH_BOLT("Earth Bolt", SpriteID.Magicon.EARTH_BOLT, AIR, EARTH, CHAOS),
    ENCHANT_TOPAZ_BOLT("Enchant Topaz Bolt", SpriteID.Magicon2.ENCHANT_CROSSBOW_BOLT, FIRE, COSMIC),
    LUMBRIDGE_TELEPORT("Lumbridge Teleport", SpriteID.Magicon.LUMBRIDGE_TELEPORT, AIR, EARTH, LAW),
    TELEKINETIC_GRAB("Telekinetic Grab", SpriteID.Magicon.TELEKINETIC_GRAB, AIR, LAW),
    RESPAWN_TELEPORT("Respawn Teleport", SpriteID.MagicNecroOn.RESPAWN_TELEPORT, LAW, SOUL),
    FIRE_BOLT("Fire Bolt", SpriteID.Magicon.FIRE_BOLT, AIR, FIRE, CHAOS),
    GHOSTLY_GRASP("Ghostly Grasp", SpriteID.MagicNecroOn.GHOSTLY_GRASP, AIR, CHAOS),
    FALADOR_TELEPORT("Falador Teleport", SpriteID.Magicon.FALADOR_TELEPORT, AIR, WATER, LAW),
    RESURRECT_LESSER_THRALL("Resurrect Lesser Thrall", SpriteID.MagicNecroOn.RESURRECT_LESSER_GHOST, AIR, COSMIC, MIND),
    CRUMBLE_UNDEAD("Crumble Undead", SpriteID.Magicon.CRUMBLE_UNDEAD, AIR, EARTH, CHAOS),
    SALVE_GRAVEYARD_TELEPORT("Salve Graveyard Teleport", SpriteID.MagicNecroOn.SALVE_GRAVEYARD_TELEPORT, LAW, SOUL),
    TELEPORT_TO_HOUSE("Teleport To House", SpriteID.Magicon2.TELEPORT_TO_HOUSE, AIR, EARTH, LAW),
    WIND_BLAST("Wind Blast", SpriteID.Magicon.WIND_BLAST, AIR, DEATH),
    ADEPT_REANIMATION("Adept Reanimation", SpriteID.MagicNecroOn.ADEPT_REANIMATION, BODY, NATURE, SOUL),
    SUPERHEAT_ITEM("Superheat Item", SpriteID.Magicon.SUPERHEAT_ITEM, FIRE, NATURE),
    INFERIOR_DEMONBANE("Inferior Demonbane", SpriteID.MagicNecroOn.INFERIOR_DEMONBANE, FIRE, CHAOS),
    CAMELOT_TELEPORT("Camelot Teleport",SpriteID.Magicon.CAMELOT_TELEPORT, AIR, LAW),
    WATER_BLAST("Water Blast", SpriteID.Magicon.WATER_BLAST, AIR, WATER, DEATH),
    SHADOW_VEIL("Shadow Veil", SpriteID.MagicNecroOn.SHADOW_VEIL, EARTH, FIRE, COSMIC),
    FENKENSTRAINS_CASTLE_TELEPORT("Fenkenstrain's Castle Teleport", SpriteID.MagicNecroOn.FENKENSTRAINS_CASTLE_TELEPORT, EARTH, LAW, SOUL),
    KOUREND_CASTLE_TELEPORT("Kourend Castle Teleport", SpriteID.Magicon2.TELEPORT_TO_KOUREND, FIRE, WATER, LAW),
    ENCHANT_RUBY_BOLT("Enchant Ruby Bolt", SpriteID.Magicon2.ENCHANT_CROSSBOW_BOLT, FIRE, BLOOD, COSMIC),
    ENCHANT_RUBY_JEWELLERY("Enchant Ruby Jewellery", SpriteID.Magicon.LVL_3_ENCHANT, FIRE, COSMIC),
    IBAN_BLAST("Iban Blast", SpriteID.Magicon.IBAN_BLAST, FIRE, DEATH),
    MAGIC_DART("Magic Dart", SpriteID.Magicon2.MAGIC_DART, DEATH, MIND),
    SMOKE_RUSH("Smoke Rush", SpriteID.Magicon2.SMOKE_RUSH, AIR, FIRE, CHAOS, DEATH),
    DARK_LURE("Dark Lure", SpriteID.MagicNecroOn.DARK_LURE, DEATH, NATURE),
    SNARE("Snare", SpriteID.Magicon2.SNARE, EARTH, WATER, NATURE),
    ARDOUGNE_TELEPORT("Ardougne Teleport", SpriteID.Magicon.ARDOUGNE_TELEPORT, WATER, LAW),
    SHADOW_RUSH("Shadow Rush", SpriteID.Magicon2.SHADOW_RUSH, AIR, CHAOS, DEATH, SOUL),
    EARTH_BLAST("Earth Blast", SpriteID.Magicon.EARTH_BLAST, AIR, EARTH, DEATH),
    CIVITAS_ILLA_FORTIS_TELEPORT("Civitas illa Fortis Teleport", SpriteID.Magicon2.CIVITAS_ILLA_FORTIS_TELEPORT, EARTH, FIRE, LAW),
    PADDEWWA_TELEPORT("Paddewwa Teleport", SpriteID.Magicon2.PADDEWWA_TELEPORT, AIR, FIRE, LAW),
    HIGH_LEVEL_ALCHEMY("High Level Alchemy", SpriteID.Magicon.HIGH_LEVEL_ALCHEMY, FIRE, NATURE),
    BLOOD_RUSH("Blood Rush", SpriteID.Magicon2.BLOOD_RUSH, BLOOD, CHAOS, DEATH),
    SKELETAL_GRASP("Skeletal Grasp", SpriteID.MagicNecroOn.SKELETAL_GRASP, EARTH, DEATH),
    CHARGE_WATER_ORB("Charge Water Orb", SpriteID.Magicon.CHARGE_WATER_ORB, WATER, COSMIC),
    ENCHANT_DIAMOND_BOLT("Enchant Diamond Bolt", SpriteID.Magicon2.ENCHANT_CROSSBOW_BOLT, EARTH, COSMIC, LAW),
    ENCHANT_DIAMOND_JEWELLERY("Enchant Diamond Jewellery", SpriteID.Magicon.LVL_4_ENCHANT, EARTH, COSMIC),
    RESURRECT_SUPERIOR_THRALL("Resurrect Superior Thrall", SpriteID.MagicNecroOn.RESURRECT_SUPERIOR_SKELETON, EARTH, COSMIC, DEATH),
    ICE_RUSH("Ice Rush", SpriteID.Magicon2.ICE_RUSH, WATER, CHAOS, DEATH),
    WATCHTOWER_TELEPORT("Watchtower Teleport", SpriteID.Magicon.WATCHTOWER_TELEPORT, EARTH, LAW),
    FIRE_BLAST("Fire Blast", SpriteID.Magicon.FIRE_BLAST, AIR, FIRE, DEATH),
    MARK_OF_DARKNESS("Mark of Darkness", SpriteID.MagicNecroOn.MARK_OF_DARKNESS, COSMIC, SOUL),
    CLAWS_OF_GUTHIX("Claws Of Guthix", SpriteID.Magicon.CLAWS_OF_GUTHIX, AIR, FIRE, BLOOD),
    FLAMES_OF_ZAMORAK("Flames Of Zamorak", SpriteID.Magicon.FLAMES_OF_ZAMORAK, AIR, FIRE, BLOOD),
    SARADOMIN_STRIKE("Saradomin Strike", SpriteID.Magicon.SARADOMIN_STRIKE, AIR, FIRE, BLOOD),
    BONES_TO_PEACHES("Bones To Peaches", SpriteID.Magicon2.BONES_TO_PEACHES, EARTH, WATER, NATURE),
    CHARGE_EARTH_ORB("Charge Earth Orb", SpriteID.Magicon.CHARGE_EARTH_ORB, EARTH, COSMIC),
    SENNTISTEN_TELEPORT("Senntisten Teleport", SpriteID.Magicon2.SENNTISTEN_TELEPORT, LAW, SOUL),
    TROLLHEIM_TELEPORT("Trollheim Teleport", SpriteID.Magicon2.TROLLHEIM_TELEPORT, FIRE, LAW),
    WEST_ARDOUGNE_TELEPORT("West Ardougne Teleport", SpriteID.MagicNecroOn.WEST_ARDOUGNE_TELEPORT, LAW, SOUL),
    SMOKE_BURST("Smoke Burst", SpriteID.Magicon2.SMOKE_BURST, AIR, FIRE, CHAOS, DEATH),
    SUPERIOR_DEMONBANE("Superior Demonbane", SpriteID.MagicNecroOn.SUPERIOR_DEMONBANE, FIRE, SOUL),
    WIND_WAVE("Wind Wave", SpriteID.Magicon.WIND_WAVE, AIR, BLOOD),
    CHARGE_FIRE_ORB("Charge Fire Orb", SpriteID.Magicon.CHARGE_FIRE_ORB, FIRE, COSMIC),
    SHADOW_BURST("Shadow Burst", SpriteID.Magicon2.SHADOW_BURST, AIR, CHAOS, DEATH, SOUL),
    TELEPORT_APE_ATOLL("Teleport Ape Atoll", SpriteID.Magicon2.TELEPORT_TO_APE_ATOLL, FIRE, WATER, LAW),
    LESSER_CORRUPTION("Lesser Corruption", SpriteID.MagicNecroOn.LESSER_CORRUPTION, DEATH, SOUL),
    WATER_WAVE("Water Wave", SpriteID.Magicon.WATER_WAVE, AIR, WATER, BLOOD),
    BAKE_PIE("Bake Pie", SpriteID.LunarMagicOn.BAKE_PIE, FIRE, WATER, ASTRAL),
    GEOMANCY("Geomancy", SpriteID.LunarMagicOn.GEOMANCY, EARTH, ASTRAL, NATURE),
    HARMONY_ISLAND_TELEPORT("Harmony Island Teleport", SpriteID.MagicNecroOn.HARMONY_ISLAND_TELEPORT, LAW, NATURE, SOUL),
    CURE_PLANT("Cure Plant", SpriteID.LunarMagicOn.CURE_PLANT, EARTH, ASTRAL),
    MONSTER_EXAMINE("Monster Examine", SpriteID.LunarMagicOn.MONSTER_EXAMINE, ASTRAL, COSMIC, MIND),
    CHARGE_AIR_ORB("Charge Air Orb", SpriteID.Magicon.CHARGE_AIR_ORB, AIR, COSMIC),
    KHARYRLL_TELEPORT("Kharyrll Teleport", SpriteID.Magicon2.KHARYRLL_TELEPORT, BLOOD, LAW),
    VILE_VIGOUR("Vile Vigour", SpriteID.MagicNecroOn.VILE_VIGOUR, AIR, SOUL),
    VULNERABILITY("Vulnerability", SpriteID.Magicon.VULNERABILITY, EARTH, WATER, SOUL),
    NPC_CONTACT("Npc Contact", SpriteID.LunarMagicOn.NPC_CONTACT, AIR, ASTRAL, COSMIC),
    BLOOD_BURST("Blood Burst", SpriteID.Magicon2.BLOOD_BURST, BLOOD, CHAOS, DEATH),
    CURE_OTHER("Cure Other", SpriteID.LunarMagicOn.CURE_OTHER, EARTH, ASTRAL, LAW),
    HUMIDIFY("Humidify", SpriteID.LunarMagicOn.HUMIDIFY, FIRE, WATER, ASTRAL),
    ENCHANT_DRAGONSTONE_BOLT("Enchant Dragonstone Bolt", SpriteID.Magicon2.ENCHANT_CROSSBOW_BOLT, EARTH, COSMIC, SOUL),
    ENCHANT_DRAGONSTONE_JEWELLERY("Enchant Dragonstone Jewellery", SpriteID.Magicon.LVL_5_ENCHANT, EARTH, WATER, COSMIC),
    MOONCLAN_TELEPORT("Moonclan Teleport", SpriteID.LunarMagicOn.MOONCLAN_TELEPORT, EARTH, ASTRAL, LAW),
    EARTH_WAVE("Earth Wave", SpriteID.Magicon.EARTH_WAVE, AIR, EARTH, BLOOD),
    ICE_BURST("Ice Burst", SpriteID.Magicon2.ICE_BURST, WATER, CHAOS, DEATH),
    TELE_GROUP_MOONCLAN("Tele Group Moonclan", SpriteID.LunarMagicOn.TELE_GROUP_MOONCLAN, EARTH, ASTRAL, LAW),
    DEGRIME("Degrime", SpriteID.MagicNecroOn.DEGRIME, EARTH, NATURE),
    CURE_ME("Cure Me", SpriteID.LunarMagicOn.CURE_ME, ASTRAL, COSMIC, LAW),
    OURANIA_TELEPORT("Ourania Teleport", SpriteID.LunarMagicOn.OURANIA_TELEPORT, EARTH, ASTRAL, LAW),
    HUNTER_KIT("Hunter Kit", SpriteID.LunarMagicOn.HUNTER_KIT, EARTH, ASTRAL),
    CEMETERY_TELEPORT("Cemetery Teleport", SpriteID.MagicNecroOn.CEMETERY_TELEPORT, BLOOD, LAW, SOUL),
    WATERBIRTH_TELEPORT("Waterbirth Teleport", SpriteID.LunarMagicOn.WATERBIRTH_TELEPORT, WATER, ASTRAL, LAW),
    LASSAR_TELEPORT("Lassar Teleport", SpriteID.Magicon2.LASSAR_TELEPORT, WATER, LAW),
    EXPERT_REANIMATION("Expert Reanimation", SpriteID.MagicNecroOn.EXPERT_REANIMATION, BLOOD, NATURE, SOUL),
    TELE_GROUP_WATERBIRTH("Tele Group Waterbirth", SpriteID.LunarMagicOn.TELE_GROUP_WATERBIRTH, WATER, ASTRAL, LAW),
    ENFEEBLE("Enfeeble", SpriteID.Magicon.ENFEEBLE, EARTH, WATER, SOUL),
    WARD_OF_ARCEUUS("Ward of Arceuus", SpriteID.MagicNecroOn.WARD_OF_ARCEUUS, COSMIC, NATURE, SOUL),
    SMOKE_BLITZ("Smoke Blitz", SpriteID.Magicon2.SMOKE_BLITZ, AIR, FIRE, BLOOD, DEATH),
    CURE_GROUP("Cure Group", SpriteID.LunarMagicOn.CURE_GROUP, ASTRAL, COSMIC, LAW),
    TELEOTHER_LUMBRIDGE("Teleother Lumbridge", SpriteID.Magicon2.TELEOTHER_LUMBRIDGE, EARTH, LAW, SOUL),
    FIRE_WAVE("Fire Wave", SpriteID.Magicon.FIRE_WAVE, AIR, FIRE, BLOOD),
    BARBARIAN_TELEPORT("Barbarian Teleport", SpriteID.LunarMagicOn.BARBARIAN_TELEPORT, FIRE, ASTRAL, LAW),
    STAT_SPY("Stat Spy", SpriteID.LunarMagicOn.STAT_SPY, ASTRAL, BODY, COSMIC),
    SHADOW_BLITZ("Shadow Blitz", SpriteID.Magicon2.SHADOW_BLITZ, AIR, BLOOD, DEATH, SOUL),
    SPIN_FLAX("Spin Flax", SpriteID.LunarMagicOn.SPIN_FLAX, AIR, ASTRAL, NATURE),
    TELE_GROUP_BARBARIAN("Tele Group Barbarian", SpriteID.LunarMagicOn.TELE_GROUP_BARBARIAN, FIRE, ASTRAL, LAW),
    RESURRECT_GREATER_THRALL("Resurrect Greater Thrall", SpriteID.MagicNecroOn.RESURRECT_GREATER_ZOMBIE, FIRE, BLOOD, COSMIC),
    SUPERGLASS_MAKE("Superglass Make", SpriteID.LunarMagicOn.SUPERGLASS_MAKE, AIR, FIRE, ASTRAL),
    KHAZARD_TELEPORT("Khazard Teleport", SpriteID.LunarMagicOn.KHAZARD_TELEPORT, WATER, ASTRAL, LAW),
    TAN_LEATHER("Tan Leather", SpriteID.LunarMagicOn.TAN_LEATHER, FIRE, ASTRAL, NATURE),
    DAREEYAK_TELEPORT("Dareeyak Teleport", SpriteID.Magicon2.DAREEYAK_TELEPORT, AIR, FIRE, LAW),
    RESURRECT_CROPS("Resurrect Crops", SpriteID.MagicNecroOn.RESURRECT_CROPS, EARTH, BLOOD, NATURE, SOUL),
    UNDEAD_GRASP("Undead Grasp", SpriteID.MagicNecroOn.UNDEAD_GRASP, FIRE, BLOOD),
    TELE_GROUP_KHAZARD("Tele Group Khazard", SpriteID.LunarMagicOn.TELE_GROUP_KHAZARD, WATER, ASTRAL, LAW),
    DREAM("Dream", SpriteID.LunarMagicOn.DREAM, ASTRAL, BODY, COSMIC),
    ENTANGLE("Entangle", SpriteID.Magicon2.ENTANGLE, EARTH, WATER, NATURE),
    BLOOD_BLITZ("Blood Blitz", SpriteID.Magicon2.BLOOD_BLITZ, BLOOD, DEATH),
    STRING_JEWELLERY("String Jewellery", SpriteID.LunarMagicOn.STRING_JEWELLERY, EARTH, WATER, ASTRAL),
    DEATH_CHARGE("Death Charge", SpriteID.MagicNecroOn.DEATH_CHARGE, BLOOD, DEATH, SOUL),
    STUN("Stun", SpriteID.Magicon.STUN, EARTH, WATER, SOUL),
    CHARGE("Charge", SpriteID.Magicon2.CHARGE, AIR, FIRE, BLOOD),
    WIND_SURGE("Wind Surge", SpriteID.Magicon2.WIND_SURGE, AIR, WRATH),
    STAT_RESTORE_POT_SHARE("Stat Restore Pot Share", SpriteID.LunarMagicOn.STAT_RESTORE_POT_SHARE, EARTH, WATER, ASTRAL),
    DARK_DEMONBANE("Dark Demonbane", SpriteID.MagicNecroOn.DARK_DEMONBANE, FIRE, SOUL),
    ICE_BLITZ("Ice Blitz", SpriteID.Magicon2.ICE_BLITZ, WATER, BLOOD, DEATH),
    MAGIC_IMBUE("Magic Imbue", SpriteID.LunarMagicOn.MAGIC_IMBUE, FIRE, WATER, ASTRAL),
    TELEOTHER_FALADOR("Teleother Falador", SpriteID.Magicon2.TELEOTHER_FALADOR, WATER, LAW, SOUL),
    FERTILE_SOIL("Fertile Soil", SpriteID.LunarMagicOn.FERTILE_SOIL, EARTH, ASTRAL, NATURE),
    BARROWS_TELEPORT("Barrows Teleport", SpriteID.MagicNecroOn.BARROWS_TELEPORT, BLOOD, LAW, SOUL),
    CARRALLANGER_TELEPORT("Carrallanger Teleport", SpriteID.Magicon2.CARRALLANGAR_TELEPORT, LAW, SOUL),
    BOOST_POTION_SHARE("Boost Potion Share", SpriteID.LunarMagicOn.BOOST_POTION_SHARE, EARTH, WATER, ASTRAL),
    DEMONIC_OFFERING("Demonic Offering", SpriteID.MagicNecroOn.DEMONIC_OFFERING, SOUL, WRATH),
    TELEPORT_TO_TARGET("Teleport To Target", SpriteID.Magicon2.TELEPORT_TO_BOUNTY_TARGET, CHAOS, DEATH, LAW),
    WATER_SURGE("Water Surge", SpriteID.Magicon2.WATER_SURGE, AIR, WATER, WRATH),
    TELE_BLOCK("Tele Block", SpriteID.Magicon2.TELE_BLOCK, CHAOS, DEATH, LAW),
    FISHING_GUILD_TELEPORT("Fishing Guild Teleport", SpriteID.LunarMagicOn.FISHING_GUILD_TELEPORT, WATER, ASTRAL, LAW),
    GREATER_CORRUPTION("Greater Corruption", SpriteID.MagicNecroOn.GREATER_CORRUPTION, BLOOD, SOUL),
    SMOKE_BARRAGE("Smoke Barrage", SpriteID.Magicon2.SMOKE_BARRAGE, AIR, FIRE, BLOOD, DEATH),
    PLANK_MAKE("Plank Make", SpriteID.LunarMagicOn.PLANK_MAKE, EARTH, ASTRAL, NATURE),
    TELE_GROUP_FISHING_GUILD("Tele Group Fishing Guild", SpriteID.LunarMagicOn.TELE_GROUP_FISHING_GUILD, WATER, ASTRAL, LAW),
    CATHERBY_TELEPORT("Catherby Teleport", SpriteID.LunarMagicOn.CATHERBY_TELEPORT, WATER, ASTRAL, LAW),
    ENCHANT_ONYX_BOLT("Enchant Onyx Bolt", SpriteID.Magicon2.ENCHANT_CROSSBOW_BOLT, FIRE, COSMIC, DEATH),
    ENCHANT_ONYX_JEWELLERY("Enchant Onyx Jewellery", SpriteID.Magicon2.LVL_6_ENCHANT, EARTH, FIRE, COSMIC),
    SHADOW_BARRAGE("Shadow Barrage", SpriteID.Magicon2.SHADOW_BARRAGE, AIR, BLOOD, DEATH, SOUL),
    TELE_GROUP_CATHERBY("Tele Group Catherby", SpriteID.LunarMagicOn.TELE_GROUP_CATHERBY, WATER, ASTRAL, LAW),
    ICE_PLATEAU_TELEPORT("Ice Plateau Teleport", SpriteID.LunarMagicOn.ICE_PLATEAU_TELEPORT, WATER, ASTRAL, LAW),
    RECHARGE_DRAGONSTONE("Recharge Dragonstone", SpriteID.LunarMagicOn.RECHARGE_DRAGONSTONE, WATER, ASTRAL, SOUL),
    EARTH_SURGE("Earth Surge", SpriteID.Magicon2.EARTH_SURGE, AIR, EARTH, WRATH),
    TELE_GROUP_ICE_PLATEAU("Tele Group Ice Plateau", SpriteID.LunarMagicOn.TELE_GROUP_ICE_PLATEAU, WATER, ASTRAL, LAW),
    ANNAKARL_TELEPORT("Annakarl Teleport", SpriteID.Magicon2.ANNAKARL_TELEPORT, BLOOD, LAW),
    APE_ATOLL_TELEPORT("Ape Atoll Teleport", SpriteID.MagicNecroOn.APE_ATOLL_TELEPORT, BLOOD, LAW, SOUL),
    TELEOTHER_CAMELOT("Teleother Camelot", SpriteID.Magicon2.TELEOTHER_CAMELOT, LAW, SOUL),
    MASTER_REANIMATION("Master Reanimation", SpriteID.MagicNecroOn.MASTER_REANIMATION, BLOOD, NATURE, SOUL),
    ENERGY_TRANSFER("Energy Transfer", SpriteID.LunarMagicOn.ENERGY_TRANSFER, ASTRAL, LAW, NATURE),
    BLOOD_BARRAGE("Blood Barrage", SpriteID.Magicon2.BLOOD_BARRAGE, BLOOD, DEATH, SOUL),
    HEAL_OTHER("Heal Other", SpriteID.LunarMagicOn.HEAL_OTHER, ASTRAL, BLOOD, LAW),
    SINISTER_OFFERING("Sinister Offering", SpriteID.MagicNecroOn.SINISTER_OFFERING, BLOOD, WRATH),
    VENGEANCE_OTHER("Vengeance Other", SpriteID.LunarMagicOn.VENGEANCE_OTHER, EARTH, ASTRAL, DEATH),
    ENCHANT_ZENYTE_JEWELLERY("Enchant Zenyte Jewellery", SpriteID.Magicon2.LVL_7_ENCHANT, BLOOD, COSMIC, SOUL),
    ICE_BARRAGE("Ice Barrage", SpriteID.Magicon2.ICE_BARRAGE, WATER, BLOOD, DEATH),
    VENGEANCE("Vengeance", SpriteID.LunarMagicOn.VENGEANCE, EARTH, ASTRAL, DEATH),
    FIRE_SURGE("Fire Surge", SpriteID.Magicon2.FIRE_SURGE, AIR, FIRE, WRATH),
    HEAL_GROUP("Heal Group", SpriteID.LunarMagicOn.HEAL_GROUP, ASTRAL, BLOOD, LAW),
    GHORROCK_TELEPORT("Ghorrock Teleport", SpriteID.Magicon2.GHORROCK_TELEPORT, WATER, LAW),
    SPELLBOOK_SWAP("Spellbook Swap", SpriteID.LunarMagicOn.SPELLBOOK_SWAP, ASTRAL, COSMIC, LAW);

    private final String spellName;
    private final int spriteID;
    private final EnumSet<RuneTypes> runes;

    SpellData(String name, int id, RuneTypes... runes)
    {
        this.spellName = name;
        this.spriteID = id;
        this.runes = EnumSet.of(runes[0], runes);
    }
}